#docker-compose -f "docker-compose.yml" up --build
version: '2'
name: 'Bank-API'
services:
  postgres:
    container_name: "Bank-API-postgres"
    ports:
      - "5432:5432"
    image: postgres:11.1
    environment:
      POSTGRES_DB: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      
  localstack:
    container_name: "Bank-API-localstack"
    image: localstack/localstack
    ports:
      - "4566:4566"
      - "8055:8080"
    environment:
      - SERVICES=s3

  kafka:
    container_name: "Bank-API-kafka"
    image: krisgeus/docker-kafka
    ports:
      - "9092:9092"
    environment:
      ADVERTISED_LISTENERS: 'INSIDE://kafka:9093,OUTSIDE://localhost:9092'
      LISTENERS: 'INSIDE://0.0.0.0:9093,OUTSIDE://0.0.0.0:9092'
      SECURITY_PROTOCOL_MAP: 'INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT'
      INTER_BROKER: 'INSIDE'
      KAFKA_CREATE_TOPICS: 'bank-api-events'